name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build frontend (Next.js)
        run: npm run build --workspace=apps/web

      - name: Start frontend server
        run: npm run start --workspace=apps/web &

      - name: Wait for frontend server to be ready
        run: |
          for i in {1..30}; do
            if curl --silent http://localhost:3000 > /dev/null; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 2
            fi
          done

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: http://localhost:3000
          uploadArtifacts: true
          artifactName: lighthouse-report

      - name: Upload Lighthouse report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./reports/lighthouse-report.html
