name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm start &

      - name: Wait for server to be ready
        run: |
          n=0
          until curl -s http://localhost:3000 > /dev/null; do
            n=$((n+1))
            if [ $n -gt 30 ]; then
              echo "Server did not start in time"
              exit 1
            fi
            sleep 2
          done

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: http://localhost:3000
          uploadArtifacts: true
          artifactName: lh-report
          runs: 1

      - name: Kill server
        run: |
          lsof -ti tcp:3000 | xargs kill -9 || true
